site_name: 腐烂的橘子
copyright: Copyright &copy; 2023 - 2024 <a href="https://github.com/z1ming" target="_blank" rel="noopener noreferrer">Rotten Orange</a>|沪ICP备2024058920号
nav:
  - 前言: index.md
  - 面试题合集:
    - 计算机网络面试题: 文章/network.md
    - Java 面试题-基础: 文章/Java-base.md
    - MySQL 高频面试题: 文章/MySQL-question.md
    - Redis 面试题: 文章/redis.md
    - 操作系统面试题: 文章/OS.md
    - Spring Boot 面试题: 文章/spring-boot.md
    - 力扣分类题集: 文章/LeetCode.md
  - 后端每日一题:
    - 后端每日一题 1：三次握手: 文章/three-hands-shake.md
  - 架构每日一学:
    - 架构每日一学 1：成为一名架构师，你必须具有“战略意图”: 文章/jiagou1.md
    - 架构每日一学 2：架构师六个生存法则之一：架构必须有且仅有一个目标（一）: 文章/jiagou2.md
  - MySQL: 
    - 哲学家就餐：死锁及解决方案 Java: 文章/DiningPhilosophers.md
    - InnoDB 锁介绍: 文章/InnoDB-Locking.md
  - Go:
    - Go 笔记: 文章/Go.md
  - 随笔:
    - 手写访问控制列表（ACL）: 文章/ACLs.md
    - 分布式全局唯一 ID 实现: 文章/id.md
    - 浅谈 LISP: 文章/LISP.md
    - 布隆过滤器: 文章/BloomFilter.md
    - JVM 参数: 文章/JVM-params.md
    - GC 垃圾回收策略: 文章/GC.md
repo_url: https://github.com/z1ming/z1ming.github.io
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto Slab
    code: Roboto Mono
language: zh
hljs_languages:
  - yaml
