site_name: 腐烂的橘子
nav:
  - 前言: index.md
  - Java:
    - Java 面试题-基础: 文章/Java-base.md
  - MySQL: 
    - MySQL 高频面试题: 文章/MySQL-question.md
    - 哲学家就餐：死锁及解决方案 Java: 文章/DiningPhilosophers.md
    - InnoDB 锁介绍: 文章/InnoDB-Locking.md
  - 算法:
    - 力扣分类题集: 文章/LeetCode.md
  - 其他文章:
    - 手写访问控制列表（ACL）: 文章/ACLs.md
    - 分布式全局唯一 ID 实现: 文章/id.md
    - 浅谈 LISP: 文章/LISP.md
repo_url: https://github.com/z1ming/z1ming.github.io
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
language: zh
hljs_languages:
  - yaml
