site_name: 腐烂的橘子
nav:
  - 知识图谱:
    - 计算机网络:
    - 操作系统:
    - 编程基础:
    - 数据库:
    - 中间件:
    - 项目:
  - 文章:
    - 手写访问控制列表（ACL）: 文章/ACLs.md
theme:
  name: material
language: zh
hljs_languages:
  - yaml
